FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env


WORKDIR /app

COPY . ./
RUN dotnet restore
RUN dotnet test
RUN dotnet publish -c Release -o output

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

EXPOSE 80
ENV ECHO_APP_NAME=default


WORKDIR /app
COPY --from=build-env /app/output .

ENTRYPOINT ["dotnet", "Echo.Api.dll"]
